syntax enable			" enable syntax highlighting

source /usr/local/lib/python2.7/site-packages/powerline/bindings/vim/plugin/powerline.vim

set nocompatible		" ensure we are using latest functionality
set hlsearch			" enable search highlighting
set incsearch			" enable search as you type
set number			" display line numbers

" indentation rules
setlocal tabstop=4 shiftwidth=4
autocmd FileType ruby setlocal expandtab tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType python setlocal expandtab tabstop=4 softtabstop=4 shiftwidth=4
autocmd FileType php setlocal expandtab tabstop=4 softtabstop=4 shiftwidth=4

set modelines=0
set visualbell
set scrolloff=3
set hidden
set laststatus=2
set showmatch
