call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'powerline/powerline', { 'rtp': 'powerline/bindings/vim/' }
Plug 'dag/vim-fish', { 'for': 'fish' }

call plug#end()

set background=dark
colorscheme solarized

set number
set visualbell
set hidden
set showmatch

setlocal tabstop=4 shiftwidth=4
autocmd FileType ruby setlocal expandtab tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType python setlocal expandtab tabstop=4 softtabstop=4 shiftwidth=4
autocmd FileType php setlocal expandtab tabstop=4 softtabstop=4 shiftwidth=4
autocmd FileType fish setlocal expandtab tabstop=2 softtabstop=2 shiftwidth=2
